# Generated by Django 6.0.6 on 2026-07-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbp', '0004_masterdatahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlocation',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Isi jika lokasi tidak terdeteksi oleh GBP API. Format: -6.200000', null=True, verbose_name='Latitude (Manual)'),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Isi jika lokasi tidak terdeteksi oleh GBP API. Format: 106.816666', null=True, verbose_name='Longitude (Manual)'),
        ),
    ]
