# Generated by Django 6.0.6 on 2026-07-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbp', '0005_add_manual_coords_to_masterlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_prefix', models.CharField(db_index=True, help_text='3 digit pertama store code cabang. Contoh: 101', max_length=10, verbose_name='Prefix Cabang (3 digit)')),
                ('branch_name', models.CharField(max_length=255, verbose_name='Nama Cabang')),
                ('area', models.CharField(blank=True, max_length=150, null=True, verbose_name='Area')),
                ('period', models.CharField(db_index=True, help_text='Format: YYYY-MM. Contoh: 2026-06', max_length=7, verbose_name='Periode (YYYY-MM)')),
                ('nsa', models.CharField(blank=True, help_text='Nominal Sales Achievement. Contoh: 333.115.001.111', max_length=100, null=True, verbose_name='NSA')),
                ('bp', models.FloatField(blank=True, help_text='Bisa positif atau negatif. Contoh: 31.59 atau -9.89', null=True, verbose_name='BP (%)')),
                ('mscp', models.FloatField(blank=True, help_text='Bisa positif atau negatif.', null=True, verbose_name='MSCP (%)')),
                ('nl', models.FloatField(blank=True, help_text='Bisa positif atau negatif.', null=True, verbose_name='NL (%)')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diupload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Branch Sales Record',
                'verbose_name_plural': 'Branch Sales Records',
                'db_table': 'gbp_branchsalesrecord',
                'ordering': ['-period', 'branch_prefix'],
                'indexes': [models.Index(fields=['branch_prefix', 'period'], name='gbp_branchs_branch__c1c921_idx')],
                'unique_together': {('branch_prefix', 'period')},
            },
        ),
    ]
